### ISSUE TITLE
Summary of DataJoint issues encountered by Brody lab and U19 members

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/bl_pipeline_python_toArchive#11]
Sorted by priority.

- [x] (Alvaro) https://github.com/datajoint/datajoint-matlab/issues/379
- [x] (Austin) https://github.com/datajoint/datajoint-labbook/issues/147
- [x] (Alvaro) https://github.com/datajoint/datajoint-python/pull/972
- [ ] (Austin) https://github.com/datajoint/datajoint-python/issues/245
- [ ] (Alvaro) https://github.com/datajoint/datajoint-docs/issues/269

**Comment by kabilar** [comment]
Hi @Alvalunasan, I was going to transfer this `Issue` to the new public [vathes](https://github.com/vathes/bl_pipeline_python) fork, and privately archive the current detached repository.  Is there any information in this `Issue` that we would not want to be in the public repository?  If so, I can delete those comments and then transfer the issue.  Thank you.

**Comment by Alvalunasan** [comment]
Hi @kabilar no I think it is fine to let all the Issue on the public repo.
Thanks for doing this.

**Comment by kabilar** [comment]
Closing as the remaining items are not currently a priority.
